language: cpp

matrix:
  include:
    - os: windows
      compiler: MSVC
    - os: linux
      dist: xenial
      compiler:
        - gcc
        - clang
    - os: osx
      compiler: clang

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
