language: cpp

jobs:
  include:
    - stage: debug-test
      os: windows
      compiler: MSVC
      before_install:
        - choco install python3 --params "/InstallDir:C:\\Python"
        - export PATH="/c/Python:/c/Python/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
        - pip install conan
    - stage: debug-test
      os: linux
      dist: xenial
      compiler:
        - gcc
        - clang
      before_install:
        - sudo apt-get install -y lcov
        - pip install conan --user
      script:
        - mkdir build && cd build
        - cmake .. -DCOVERAGE=1
        - cmake --build .
        - ./Debug/BPF.Tests
        - cat ../Tests.Console/InputFile | ./Debug/BPF.Tests.Console > testlog
        - diff testlog ../Tests.Console/OutputFile
        - cat ../Tests.Console/InputFileCrash | ./Debug/BPF.Tests.Console > testlog
        - diff testlog ../Tests.Console/OutputFileCrash
        - lcov --capture --directory . --output-file coverage.info
        - lcov --remove coverage.info '/usr/*' --output-file coverage.info
        - lcov --remove coverage.info '*/gtest/*' --output-file coverage.info
        - lcov --remove coverage.info '*Tests/*' --output-file coverage.info
        - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
    - stage: debug-test
      os: osx
      compiler: clang
      before_install:
        - pip install conan
script:
  - mkdir build && cd build
  - cmake ..
  - cmake --build .
  - ./Debug/BPF.Tests
  - cat ../Tests.Console/InputFile | ./Debug/BPF.Tests.Console > testlog
  - diff testlog ../Tests.Console/OutputFile
  - cat ../Tests.Console/InputFileCrash | ./Debug/BPF.Tests.Console > testlog
  - diff testlog ../Tests.Console/OutputFileCrash
