bp_add_definition("MAC")
set(BP_SYMBOL_IMPORT_MACRO "__attribute__((visibility(\"default\")))")
set(BP_SYMBOL_EXPORT_MACRO ${BP_SYMBOL_IMPORT_MACRO})
set(BP_EXTENSION_DYNAMIC ".dylib")
set(BP_EXYENSION_STATIC ".a")
set(BP_EXTENSION_LIB ".dylib")
set(BP_LIBRARY_PREFIX "lib")

function(bp_target_created name)
endfunction(bp_target_created)
