name: 'Periodic Artifact Cleanup'

on:
  schedule:
    - cron: '* * * * 1' # every hour

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 1week # Setting this to 0 will delete all artifacts
